import { Card } from "../shared/types";

const cards: Card[] = [
  {
    id: "1",
    name: "Crowbar",
    canOpenDoorsWithoutNoise: true,
    canOpenDoorsWithNoise: false,
    createsNoiseWhenAttacking: false,
    minRange: 0,
    maxRange: 0,
    numberOfDice: 1,
    rollRequired: 4,
    damage: 1,
    rarity: "common",
  },
  {
    id: "2",
    name: "Fire Axe",
    canOpenDoorsWithoutNoise: false,
    canOpenDoorsWithNoise: true,
    createsNoiseWhenAttacking: false,
    minRange: 0,
    maxRange: 0,
    numberOfDice: 1,
    rollRequired: 4,
    damage: 2,
    rarity: "common",
  },
  {
    id: "3",
    name: "Pan",
    canOpenDoorsWithoutNoise: false,
    canOpenDoorsWithNoise: false,
    createsNoiseWhenAttacking: false,
    minRange: 0,
    maxRange: 0,
    numberOfDice: 1,
    rollRequired: 6,
    damage: 1,
    rarity: "common",
  },
  {
    id: "4",
    name: "Pistol",
    canOpenDoorsWithoutNoise: false,
    canOpenDoorsWithNoise: false,
    createsNoiseWhenAttacking: true,
    minRange: 0,
    maxRange: 1,
    numberOfDice: 1,
    rollRequired: 4,
    damage: 1,
    rarity: "uncommon",
  },
  {
    id: "5",
    name: "Rifle",
    canOpenDoorsWithoutNoise: false,
    canOpenDoorsWithNoise: false,
    createsNoiseWhenAttacking: true,
    minRange: 1,
    maxRange: 3,
    numberOfDice: 1,
    rollRequired: 3,
    damage: 1,
    rarity: "rare",
  },
];

export { cards };
