// Generated by v0

import { usePlayerStore } from "../../store/usePlayerStore";
import { Button } from "../UI/Button";

const ActionsRemaining = () => {
  const actionsRemaining = usePlayerStore((state) => state.actionsRemaining);
  const totalActions = usePlayerStore((state) => state.totalActions);

  const isMyTurn = usePlayerStore((state) => state.isMyTurn);

  const handleEndTurn = () => {
    console.log("end turn");
  };

  return (
    <div className="space-y-4">
      <h4 className="text-red-400 font-bold text-center tracking-wider border-b border-red-900/50 pb-2 font-mono">
        ACTIONS LEFT
      </h4>
      <div className="text-center">
        <div className="text-4xl font-bold text-red-500 mb-4 drop-shadow-lg font-mono">
          {actionsRemaining}
        </div>
        <div className="grid grid-cols-2 gap-2">
          {Array.from({ length: totalActions }, (_, i) => i + 1).map(
            (actionNum) => (
              <div
                key={actionNum}
                className={`p-3 text-left font-bold transition-all duration-300 font-mono rounded-[50px] ${
                  actionNum <= actionsRemaining
                    ? "bg-gradient-to-b from-red-800/80 to-red-900/90 text-red-100 border-2 border-red-600/60 shadow-lg"
                    : "bg-gradient-to-b from-stone-800/80 to-stone-900/90 text-stone-500 border-2 border-stone-700/40"
                }`}
              >
                {actionNum}
              </div>
            )
          )}
        </div>
      </div>
      {isMyTurn ? (
        <div className="flex justify-center items-center mt-4">
          <Button
            onClick={handleEndTurn}
            variant="destructive"
            size="lg"
            className="px-6 py-3 text-lg font-bold tracking-wide font-mono transition-all duration-200 hover:scale-105 shadow-md hover:shadow-lg bg-gradient-to-b from-red-600 to-red-700 hover:from-red-500 hover:to-red-600 animate-pulse border border-red-400/30"
          >
            🗡️ END TURN
          </Button>
        </div>
      ) : null}
    </div>
  );
};

export default ActionsRemaining;
